config:
  serverConfig:
    http-server.http.enabled: false
    http-server.https.enabled: true
    http-server.https.port: 8443
    http-server.https.keystore.path: /etc/certificates/cert.pem
    monitor.http-client.trust-store-path: /etc/certificates/cert.crt
    proxy.http-client.trust-store-path: /etc/certificates/cert.crt
  dataStore:
    # The connection details for the backend database for Trino Gateway and Trino query history
    jdbcUrl: jdbc:postgresql://gateway-backend-db-postgresql.default.svc.cluster.local:5432/gateway
    user: gateway
    password: pass0000
    driver: org.postgresql.Driver


volumes:
  - name: certificates
    secret:
      secretName: certificates

volumeMounts:
  - name: certificates
    mountPath: /etc/certificates
    readOnly: true
