apiVersion: v1
kind: Pod
metadata:
  name: init-gateway-db
  labels:
    app.kubernetes.io/component: test
spec:
  initContainers:
    - name: extract-persistence-sql
      image: "trinodb/trino-gateway"
      command:
        - "/bin/sh"
        - "-c"
        - |
          cd /etc/persistence && \
          jar -xvf /usr/lib/trino/gateway-ha-jar-with-dependencies.jar \
          gateway-ha-persistence-postgres.sql
      volumeMounts:
        - name: persistence-sql
          mountPath: /etc/persistence
  containers:
    - name: initialize-db
      image: bitnami/postgresql:17.1.0
      command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Initialize gateway schema";
          PGPASSWORD=pass0000 psql \
          -h gateway-backend-db-postgresql.default.svc.cluster.local \
          -U gateway -d gateway \
          -f /etc/persistence/gateway-ha-persistence-postgres.sql
      volumeMounts:
        - name: persistence-sql
          mountPath: /etc/persistence
  volumes:
    - name: persistence-sql
      emptyDir:
        sizeLimit: 10Mi

  restartPolicy: Never
