apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-conf
data:
  krb5.conf: |
   [libdefaults]
     default_realm = EXAMPLE.COM
     dns_lookup_realm = false
     dns_lookup_kdc = true
     rdns = false
     ticket_lifetime = 24h
     forwardable = true
     udp_preference_limit = 0
     permitted_enctypes = aes256-cts-hmac-sha1-96 aes256-cts-hmac-sha384-192 camellia256-cts-cmac aes128-cts-hmac-sha1-96 aes128-cts-hmac-sha256-128 camellia128-cts-cmac
   [realms]
     EXAMPLE.COM = {
       kdc = kuberos-kuberos-kdc.test.svc.cluster.local:88
       master_kdc = kuberos-kuberos-kdc.test.svc.cluster.local:88
       admin_server = kuberos-kuberos-kadmin.test.svc.cluster.local:749
       default_domain = cluster.local
       ; pkinit_anchors = FILE:/path/to/kdc-ca-bundle.pem
       ; pkinit_pool = FILE:/path/to/ca-bundle.pem
      }
   [domain_realm]
       .test.svc.cluster.local = EXAMPLE.COM
       test.svc.cluster.local = EXAMPLE.COM
